server:
  port: 8000
spring:
  cloud:
    gateway:
      routes:
        - id: auth
          uri: lb://xiaohongshu-auth
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1